---
Name: wf-userforms
Only:
  ModuleExists: userforms
---
UserDefinedForm:
  extensions:
    - OriginalContentExtension
    - WebFoxUserFormExtension

EditableDropdown:
  extensions:
    - EditableDropdownExtension