---
Name: webfox-userforms
Only:
  ModuleExists: userforms
---
UserDefinedForm:
  extensions:
    - OriginalContentExtension
    - WebFoxUserDefinedFormExtension

UserForm:
  extensions:
    - WebFoxUserFormExtension

EditableDropdown:
  extensions:
    - EditableDropdownExtension
