---
Name: wf-userforms
Only:
  ModuleExists: userforms
---
UserDefinedForm:
  extensions:
    - OriginalContentExtension

UserDefinedForm_Controller:
  extensions:
    - ApplyWebfoxUserformsOverrides

EditableDropdown:
  extensions:
    - EditableDropdownExtension